create database DBPostoABC;


create table tanque (
  idTanque integer generated by default as identity primary key,
  Descricao varchar(40)  
);

create table bomba (
  idBomba integer generated by default as identity primary key,
  descricao varchar(40),
  idtanque integer   
);

create table abastecimento (
  idAbas integer generated by default as identity primary key,
  idBomba integer,
  litros numeric(5,2),
  valor numeric(10,2),
  imposto numeric(10,2),
  vlimposto numeric(10,2),
  vllitro numeric(10,2),
  dataAbastecimento TIMESTAMP 
);


ALTER TABLE ABASTECIMENTO
ADD CONSTRAINT FK_ABASTECIMENTO_1
FOREIGN KEY (IDBOMBA)
REFERENCES BOMBA(IDBOMBA);

ALTER TABLE BOMBA
ADD CONSTRAINT FK_BOMBA_1
FOREIGN KEY (IDTANQUE)
REFERENCES TANQUE(IDTANQUE);